### ISSUE TITLE
期待vue版本~🥰 [FEATURE]

### ISSUE THREAD

**Issue by xiaonanfeng** [antvis/L7Editor#35]
### 💻 Features description [Please make everyone to understand it]
期待官方出一个vue版本~

**Comment by heiyexing** [comment]
L7Editor 主要是依靠 L7 的 React 组件库 [LarkMap](https://larkmap.antv.antgroup.com/) 搭建的，要输出 Vue 版本首先需要输出 L7 的 Vue 组件库，同学有兴趣一起来共建吗

**Comment by hustcc** [comment]
> L7Editor 主要是依靠 L7 的 React 组件库 [LarkMap](https://larkmap.antv.antgroup.com/) 搭建的，要输出 Vue 版本首先需要输出 L7 的 Vue 组件库，同学有兴趣一起来共建吗

还有一个方案，就是把 React ReactDOM 也一起打包，这样就可以在 vue 中使用了！
