### ISSUE TITLE
添加距离测量功能

### ISSUE THREAD

**Issue by zcwww1996** [antvis/L7Editor#42]
希望添加测量两个坐标点之间的直线距离的功能，目前无法判断多个polygon图形的距离是否是正确的值，如果想知道一个polygon扩大100米后的几何图形是否正确，还需要在高德地图再测量一遍，非常不方便

**Comment by heiyexing** [comment]
已支持
![image](https://github.com/antvis/L7Editor/assets/29321750/79689240-875f-4b3c-b87a-d4ef0d16f8af)
![image](https://github.com/antvis/L7Editor/assets/29321750/4f9f2419-839f-44c0-8e49-5f926cb25d31)
